// Package ptyclient re-exports github.com/AG-Studio-Apps/mtroamd/pkg/client.
//
// The implementation moved to github.com/AG-Studio-Apps/mtroamd/pkg/client so code outside this module can
// import it; Go forbids importing internal/. This file exists purely so that
// upstream files which still import the internal path keep compiling untouched,
// which keeps the rebase surface against upstream small. Do not add logic here.
//
// Code generated by hand-run shimgen. DO NOT EDIT.

package ptyclient

import cc "github.com/AG-Studio-Apps/mtroamd/pkg/client"

type (
	ChildExit   = cc.ChildExit
	Conn        = cc.Conn
	SpawnConfig = cc.SpawnConfig
)

var (
	Discover       = cc.Discover
	SpawnNew       = cc.SpawnNew
	ErrSidecarBusy = cc.ErrSidecarBusy
	ErrSidecarGone = cc.ErrSidecarGone
)
