// Package protocol re-exports github.com/AG-Studio-Apps/mtroamd/pkg/protocol.
//
// The implementation moved to github.com/AG-Studio-Apps/mtroamd/pkg/protocol so code outside this module can
// import it; Go forbids importing internal/. This file exists purely so that
// upstream files which still import the internal path keep compiling untouched,
// which keeps the rebase surface against upstream small. Do not add logic here.
//
// Code generated by hand-run shimgen. DO NOT EDIT.

package protocol

import pp "github.com/AG-Studio-Apps/mtroamd/pkg/protocol"

type (
	Ack             = pp.Ack
	AgentNotify     = pp.AgentNotify
	Attach          = pp.Attach
	AttachAck       = pp.AttachAck
	EchoConfirm     = pp.EchoConfirm
	Goodbye         = pp.Goodbye
	Ping            = pp.Ping
	Pong            = pp.Pong
	RTTNotify       = pp.RTTNotify
	Recover         = pp.Recover
	RecoverProgress = pp.RecoverProgress
	Resize          = pp.Resize
	WedgeDetected   = pp.WedgeDetected
)

const (
	ALPN                        = pp.ALPN
	AttachErrBadToken           = pp.AttachErrBadToken
	AttachErrCapacity           = pp.AttachErrCapacity
	AttachErrReplaced           = pp.AttachErrReplaced
	AttachErrUnknownSession     = pp.AttachErrUnknownSession
	AttachErrVersionUnsupported = pp.AttachErrVersionUnsupported
	AttachModeExclusive         = pp.AttachModeExclusive
	AttachModeExclusiveIfFree   = pp.AttachModeExclusiveIfFree
	AttachModePassive           = pp.AttachModePassive
	AttachModeReadonly          = pp.AttachModeReadonly
	EchoStateOff                = pp.EchoStateOff
	EchoStateOn                 = pp.EchoStateOn
	EchoStateUnknown            = pp.EchoStateUnknown
	ErrBadFrame                 = pp.ErrBadFrame
	ErrBadToken                 = pp.ErrBadToken
	ErrInternal                 = pp.ErrInternal
	ErrOversizedDatagram        = pp.ErrOversizedDatagram
	ErrOversizedFrame           = pp.ErrOversizedFrame
	ErrProtocolViolation        = pp.ErrProtocolViolation
	ErrStreamWrongOrder         = pp.ErrStreamWrongOrder
	FrameTypeControl            = pp.FrameTypeControl
	FrameTypeStdin              = pp.FrameTypeStdin
	FrameTypeStdout             = pp.FrameTypeStdout
	MaxControlFrameBytes        = pp.MaxControlFrameBytes
	MaxDatagramBytes            = pp.MaxDatagramBytes
	MaxOutputFramePayload       = pp.MaxOutputFramePayload
	ReasonClientClose           = pp.ReasonClientClose
	ReasonError                 = pp.ReasonError
	ReasonReplaced              = pp.ReasonReplaced
	ReasonSessionEnded          = pp.ReasonSessionEnded
	ReasonShutdown              = pp.ReasonShutdown
	RecoverStageDone            = pp.RecoverStageDone
	RecoverStageError           = pp.RecoverStageError
	RecoverStageExiting         = pp.RecoverStageExiting
	RecoverStageRestarting      = pp.RecoverStageRestarting
	RecoverStageSaving          = pp.RecoverStageSaving
	RecoverStageStarted         = pp.RecoverStageStarted
	TypeAck                     = pp.TypeAck
	TypeAgentNotify             = pp.TypeAgentNotify
	TypeAttach                  = pp.TypeAttach
	TypeAttachAck               = pp.TypeAttachAck
	TypeEchoConfirm             = pp.TypeEchoConfirm
	TypeGoodbye                 = pp.TypeGoodbye
	TypePing                    = pp.TypePing
	TypePong                    = pp.TypePong
	TypeRTTNotify               = pp.TypeRTTNotify
	TypeRecover                 = pp.TypeRecover
	TypeRecoverProgress         = pp.TypeRecoverProgress
	TypeResize                  = pp.TypeResize
	TypeWedgeDetected           = pp.TypeWedgeDetected
)

var (
	DecodeOutputFrame      = pp.DecodeOutputFrame
	DecodeStdoutBody       = pp.DecodeStdoutBody
	EncodeOutputFrame      = pp.EncodeOutputFrame
	EncodeStdoutBody       = pp.EncodeStdoutBody
	MarshalAck             = pp.MarshalAck
	MarshalAgentNotify     = pp.MarshalAgentNotify
	MarshalAttach          = pp.MarshalAttach
	MarshalAttachAck       = pp.MarshalAttachAck
	MarshalEchoConfirm     = pp.MarshalEchoConfirm
	MarshalGoodbye         = pp.MarshalGoodbye
	MarshalPing            = pp.MarshalPing
	MarshalPong            = pp.MarshalPong
	MarshalRTTNotify       = pp.MarshalRTTNotify
	MarshalRecover         = pp.MarshalRecover
	MarshalRecoverProgress = pp.MarshalRecoverProgress
	MarshalResize          = pp.MarshalResize
	MarshalWedgeDetected   = pp.MarshalWedgeDetected
	PeekType               = pp.PeekType
	ReadFrame              = pp.ReadFrame
	ReadTaggedFrame        = pp.ReadTaggedFrame
	WriteFrame             = pp.WriteFrame
	WriteTaggedFrame       = pp.WriteTaggedFrame
	StrictDecMode          = pp.StrictDecMode
)
